// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGEuOAAZOYhhqn0fKo_-LQBjj5umujj9U',
    appId: '1:770236588692:web:12d81e1c67f5349cb20a81',
    messagingSenderId: '770236588692',
    projectId: 'basicauthapp-6adcf',
    authDomain: 'basicauthapp-6adcf.firebaseapp.com',
    storageBucket: 'basicauthapp-6adcf.firebasestorage.app',
    measurementId: 'G-JRNYT0LC1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADjDLdApgRNqFKI6NMdtfMUeOi2A20d1s',
    appId: '1:770236588692:android:3c8cd5153ee32f21b20a81',
    messagingSenderId: '770236588692',
    projectId: 'basicauthapp-6adcf',
    storageBucket: 'basicauthapp-6adcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjZmknWgWW3hq7PFS3M0xH1C2Skailcnw',
    appId: '1:770236588692:ios:25b568cf3945b1ecb20a81',
    messagingSenderId: '770236588692',
    projectId: 'basicauthapp-6adcf',
    storageBucket: 'basicauthapp-6adcf.firebasestorage.app',
    iosBundleId: 'com.example.basicAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGEuOAAZOYhhqn0fKo_-LQBjj5umujj9U',
    appId: '1:770236588692:web:8d93a5e8b0825c33b20a81',
    messagingSenderId: '770236588692',
    projectId: 'basicauthapp-6adcf',
    authDomain: 'basicauthapp-6adcf.firebaseapp.com',
    storageBucket: 'basicauthapp-6adcf.firebasestorage.app',
    measurementId: 'G-EM6VZ0G2VR',
  );
}
